name: "career-seekers-1"
services:
  ci:
    image: openjdk:21-jdk-slim
    container_name: ci
    ports:
      - "8010:8010"
    entrypoint: /bin/bash /home/startup.sh
    volumes:
      - ./docker:/home/
    networks:
      - ci
networks:
  ci:
